name: CI - Testes Automatizados

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código
      uses: actions/checkout@v3

    - name: Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: none

    - name: Instalar dependências
      run: composer install --no-interaction --prefer-dist

    - name: Garantir PHPUnit instalado
      run: composer require --dev phpunit/phpunit ^10 || true

    - name: Rodar PHPUnit
      run: ./vendor/bin/phpunit --testdox
